# Generated by Django 2.2.7 on 2019-11-25 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRF', 'Draft'), ('PUB', 'Published'), ('CLO', 'Closed'), ('EXP', 'Expired')], max_length=3)),
                ('location_type', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=70)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='jobs.Company')),
                ('tags', models.ManyToManyField(to='jobs.JobTag')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Company')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(through='jobs.CompanyMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
